version: "3.3"
services:
  # Spring Boot application
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  # MongoDB
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
